import Link from 'next/link';
import styles from '../legal.module.css';

export const metadata = {
  title: 'Terms of Service — Summer',
  description: 'Terms governing use of Summer.',
};

export default function TermsPage() {
  return (
    <div className={styles['page']}>
      <Link href="/" className={styles['back-link']}>
        ← Back
      </Link>
      <h1 className={styles['title']}>Terms of Service</h1>
      <p className={styles['updated']}>Last updated: April 28, 2026</p>

      <p>
        Summer is a small personal-scale service that summarises receipts and
        invoices from your Gmail inbox. By signing in you agree to these terms.
      </p>

      <h2>The service</h2>
      <p>
        Summer reads purchase-related messages from the Gmail account you sign in
        with, extracts receipt details, and emails a summary back to that same
        account. It is provided as-is, on a best-effort basis, with no
        availability or accuracy guarantees.
      </p>

      <h2>Your responsibilities</h2>
      <ul>
        <li>You must own or be authorised to use the Google account you sign in with.</li>
        <li>Don&apos;t attempt to abuse, overload, or reverse-engineer the service.</li>
        <li>Don&apos;t use the service to process data you aren&apos;t entitled to access.</li>
      </ul>

      <h2>OAuth scopes</h2>
      <p>
        Summer requests <code>gmail.readonly</code> and <code>gmail.send</code>
        from Google. The read scope is used to fetch candidate receipt messages;
        the send scope is used solely to deliver the summary back to your own
        inbox. You can revoke either at any time via{' '}
        <a href="https://myaccount.google.com/permissions">
          myaccount.google.com/permissions
        </a>
        .
      </p>

      <h2>No warranty</h2>
      <p>
        The service is provided &quot;as is&quot; without warranty of any kind,
        express or implied. The receipt summary is generated by an LLM and may
        miss, misclassify, or misread items. Always check the source emails
        before relying on the totals for any consequential decision.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, the operator of Summer will not
        be liable for any indirect, incidental, special, consequential, or
        punitive damages arising from your use of the service.
      </p>

      <h2>Termination</h2>
      <p>
        You may stop using Summer at any time and revoke its Gmail access via
        your Google account. The operator may suspend or terminate access if the
        service is being misused or if continued operation becomes impractical.
      </p>

      <h2>Changes</h2>
      <p>
        These terms may change as the service evolves. Material changes will be
        reflected by updating the &ldquo;Last updated&rdquo; date above.
      </p>

      <h2>Contact</h2>
      <p>
        Questions: <a href="mailto:yariv@riser.co.il">yariv@riser.co.il</a>.
      </p>
    </div>
  );
}
